sudo: required
language: python

python:
  - "2.7"

services:
  - docker

addons:
  postgresql: "9.4"

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_script:
  - psql -c "CREATE DATABASE cloudcv" -U postgres

before_install:
  - pip install -U pip
  - nvm install 6.0.0
  - nvm use 6.0.0
  - npm install -g yarn@0.23.4

install:
  - pip install -r requirements/dev.txt
  - cd frontend && yarn install
  - cd ../

script:
  - flake8 ./
  - python manage.py test --settings=settings.test.settings
  - cd frontend && npm run lint:build
  - npm run test
  - npm run build:alias

after_success:
  - cd ../
  - pip install awscli
  - bash scripts/stage.sh
  - bash scripts/deploy.sh

cache:
  directories:
    - frontend/node_modules
    - $HOME/.cache/pip

