version: "2"
services:
  db:
    container_name: db
    hostname: db
    image: postgres
  django:
    container_name: django
    hostname: django
    env_file:
      - docker/dev.env
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    command: /code/docker/dev/django/container-start.sh
    ports:
        - "8000:8000"
    depends_on:
      - db
  nodejs:
    container_name: nodejs
    hostname: nodejs
    env_file:
      - docker/dev.env
    build:
      context: ./
      dockerfile: docker/dev/nodejs/Dockerfile
    environment:
      NODE_ENV: development
    ports:
        - "6003:6003"
    depends_on:
      - django
