# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
