# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_team_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('Team', 'Team'), ('GSoC Students, Mentors and Interns', 'GSoC Students, Mentors and Interns'), ('Contributors', 'Contributors')], max_length=50),
        ),
    ]
