# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('demo_url', models.URLField(max_length=100)),
                ('tag_line', models.CharField(blank=True, max_length=140, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('source_code_url', models.URLField(blank=True, max_length=100, null=True)),
                ('paper_description', models.CharField(blank=True, max_length=200, null=True)),
                ('paper_url', models.URLField(blank=True, max_length=100, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('sample', models.BooleanField(default=False)),
                ('text_inputs', models.IntegerField()),
                ('image_inputs', models.IntegerField()),
                ('text_outputs', models.IntegerField()),
                ('image_outputs', models.IntegerField()),
            ],
            options={
                'db_table': 'demos',
            },
        ),
    ]
