# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='demo_base_url',
            field=models.URLField(default='permalink', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demo',
            name='permalink',
            field=models.CharField(default='permalink', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demo',
            name='demo_url',
            field=models.URLField(),
        ),
    ]
