# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_auto_20170801_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('project_url', models.URLField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team')),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
