# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='from_origami',
            field=models.BooleanField(default=True),
        ),
    ]
